apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"test-pvc","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"managed-csi"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
      volume.kubernetes.io/selected-node: aks-default-20989425-vmss000000
      volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
    creationTimestamp: "2026-01-09T11:57:42Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-pvc
    namespace: default
    resourceVersion: "4779"
    uid: ec9e6016-c74d-4e16-9c26-4ceec45fccf2
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: managed-csi
    volumeMode: Filesystem
    volumeName: pvc-ec9e6016-c74d-4e16-9c26-4ceec45fccf2
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
